apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.Service.name }}"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    project: {{ .Release.Name }}
  type: NodePort
  ports:
    - name: web
      port: {{ .Values.Ports.Port }}
      nodePort: {{ .Values.Ports.NodePort }}
